### ISSUE TITLE
TODO pk-pai

### ISSUE THREAD

**Issue by tzch96** [tzch96/pk-pai#1]
- [ ] refactor
- [ ] fix the code style to be consistent across files and to get rid of unneeded complexity
- [ ] add course management functionality to admin panel
- [ ] finish lesson functionality (add flashcards and tests)
- [ ] implement course completion percentage
- [ ] make the user able to edit his account data
- [ ] implement user profile system
- [ ] make it possible for the users to submit their own course proposals
